# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 713)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_pass2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_pass2.setGeometry(QtCore.QRect(280, 380, 561, 271))
        self.tableWidget_pass2.setObjectName("tableWidget_pass2")
        self.tableWidget_pass2.setColumnCount(0)
        self.tableWidget_pass2.setRowCount(0)
        self.tableWidget_pass1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_pass1.setGeometry(QtCore.QRect(280, 20, 561, 191))
        self.tableWidget_pass1.setObjectName("tableWidget_pass1")
        self.tableWidget_pass1.setColumnCount(0)
        self.tableWidget_pass1.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 258, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_R = QtWidgets.QLabel(self.layoutWidget)
        self.label_R.setObjectName("label_R")
        self.gridLayout.addWidget(self.label_R, 0, 2, 1, 1)
        self.spinBox_R = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_R.setProperty("value", 4)
        self.spinBox_R.setObjectName("spinBox_R")
        self.gridLayout.addWidget(self.spinBox_R, 0, 3, 1, 1)
        self.pushButton_genCombinations = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_genCombinations.setObjectName("pushButton_genCombinations")
        self.gridLayout.addWidget(self.pushButton_genCombinations, 1, 0, 1, 4)
        self.spinBox_N = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_N.setProperty("value", 9)
        self.spinBox_N.setObjectName("spinBox_N")
        self.gridLayout.addWidget(self.spinBox_N, 0, 1, 1, 1)
        self.label_N = QtWidgets.QLabel(self.layoutWidget)
        self.label_N.setObjectName("label_N")
        self.gridLayout.addWidget(self.label_N, 0, 0, 1, 1)
        self.textBrowser_pass1stats = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_pass1stats.setEnabled(False)
        self.textBrowser_pass1stats.setObjectName("textBrowser_pass1stats")
        self.gridLayout.addWidget(self.textBrowser_pass1stats, 2, 0, 1, 4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 261, 56))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Method = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Method.setObjectName("label_Method")
        self.gridLayout_2.addWidget(self.label_Method, 0, 1, 1, 1)
        self.comboBox_method = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_method.setMaxVisibleItems(3)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_method, 0, 2, 1, 1)
        self.pushButton_swap = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_swap.setObjectName("pushButton_swap")
        self.gridLayout_2.addWidget(self.pushButton_swap, 1, 1, 1, 1)
        self.pushButton_Rearrange = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Rearrange.setObjectName("pushButton_Rearrange")
        self.gridLayout_2.addWidget(self.pushButton_Rearrange, 1, 2, 1, 1)
        self.tableWidget_pass2_stats = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_pass2_stats.setGeometry(QtCore.QRect(10, 380, 261, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_pass2_stats.sizePolicy().hasHeightForWidth())
        self.tableWidget_pass2_stats.setSizePolicy(sizePolicy)
        self.tableWidget_pass2_stats.setObjectName("tableWidget_pass2_stats")
        self.tableWidget_pass2_stats.setColumnCount(0)
        self.tableWidget_pass2_stats.setRowCount(0)
        self.tableWidget_pass2_freq = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_pass2_freq.setGeometry(QtCore.QRect(280, 220, 561, 151))
        self.tableWidget_pass2_freq.setObjectName("tableWidget_pass2_freq")
        self.tableWidget_pass2_freq.setColumnCount(0)
        self.tableWidget_pass2_freq.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Combinatorics-Unified"))
        self.label_R.setText(_translate("MainWindow", "R:"))
        self.pushButton_genCombinations.setText(_translate("MainWindow", "Generate Combinations"))
        self.label_N.setText(_translate("MainWindow", "N:"))
        self.label_Method.setText(_translate("MainWindow", "Method"))
        self.comboBox_method.setCurrentText(_translate("MainWindow", "bruiteforce"))
        self.comboBox_method.setItemText(0, _translate("MainWindow", "bruiteforce"))
        self.pushButton_swap.setText(_translate("MainWindow", "Swap [F8]"))
        self.pushButton_swap.setShortcut(_translate("MainWindow", "F8"))
        self.pushButton_Rearrange.setText(_translate("MainWindow", "<Apply Method>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport.setText(_translate("MainWindow", "&Import"))
        self.actionExport.setText(_translate("MainWindow", "E&xport"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
